app_identifier "friesapps.alexanimal"
metadata_path "./fastlane/metadata"
screenshots_path "./fastlane/screenshots"

skip_binary_upload true
skip_app_version_update true
skip_screenshots true
force true
overwrite_screenshots true
submit_for_review false
automatic_release false

run_precheck_before_submit false
precheck_include_in_app_purchases false

