default_platform(:ios)

platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_IDENTIFIER"] || "DNFJRPKQ53",
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"] || "c96e29b5-2cb2-4af5-a025-37cafe27c058",
      key_filepath: ENV["CM_BUILD_DIR"] ? "#{ENV["CM_BUILD_DIR"]}/fastlane/keys/AuthKey.p8" : "fastlane/keys/AuthKey.p8",
      in_house: false
    )

    deliver(
      api_key: api_key,
      app_identifier: "poolchemistry.matthijsriemsdijk",
      skip_binary_upload: true,
      skip_app_version_update: true,
      skip_screenshots: false,
      skip_metadata: false,
      overwrite_screenshots: true,
      submit_for_review: false,
      automatic_release: false,
      metadata_path: "./fastlane/metadata",
      screenshots_path: "./fastlane/screenshots",
      force: true
    )
  end
end
